// Code generated by MockGen. DO NOT EDIT.
// Source: handler.go

// Package mock_like_post is a generated GoMock package.
package mock_like_post

import (
	model "escalateservice/internal/model/domain"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockService is a mock of Service interface.
type MockService struct {
	ctrl     *gomock.Controller
	recorder *MockServiceMockRecorder
}

// MockServiceMockRecorder is the mock recorder for MockService.
type MockServiceMockRecorder struct {
	mock *MockService
}

// NewMockService creates a new mock instance.
func NewMockService(ctrl *gomock.Controller) *MockService {
	mock := &MockService{ctrl: ctrl}
	mock.recorder = &MockServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockService) EXPECT() *MockServiceMockRecorder {
	return m.recorder
}

// AddLikePost mocks base method.
func (m *MockService) AddLikePost(data *model.LikePost) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "AddLikePost", data)
}

// AddLikePost indicates an expected call of AddLikePost.
func (mr *MockServiceMockRecorder) AddLikePost(data interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddLikePost", reflect.TypeOf((*MockService)(nil).AddLikePost), data)
}
