// Code generated by MockGen. DO NOT EDIT.
// Source: handler.go

// Package mock_unfollow_user is a generated GoMock package.
package mock_unfollow_user

import (
	model "escalateservice/internal/model/domain"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockService is a mock of Service interface.
type MockService struct {
	ctrl     *gomock.Controller
	recorder *MockServiceMockRecorder
}

// MockServiceMockRecorder is the mock recorder for MockService.
type MockServiceMockRecorder struct {
	mock *MockService
}

// NewMockService creates a new mock instance.
func NewMockService(ctrl *gomock.Controller) *MockService {
	mock := &MockService{ctrl: ctrl}
	mock.recorder = &MockServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockService) EXPECT() *MockServiceMockRecorder {
	return m.recorder
}

// RemoveFollow mocks base method.
func (m *MockService) RemoveFollow(data *model.Follow) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "RemoveFollow", data)
}

// RemoveFollow indicates an expected call of RemoveFollow.
func (mr *MockServiceMockRecorder) RemoveFollow(data interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RemoveFollow", reflect.TypeOf((*MockService)(nil).RemoveFollow), data)
}
