// Code generated by MockGen. DO NOT EDIT.
// Source: handler.go

// Package mock_review_created is a generated GoMock package.
package mock_review_created

import (
	model "escalateservice/internal/model/domain"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockService is a mock of Service interface.
type MockService struct {
	ctrl     *gomock.Controller
	recorder *MockServiceMockRecorder
}

// MockServiceMockRecorder is the mock recorder for MockService.
type MockServiceMockRecorder struct {
	mock *MockService
}

// NewMockService creates a new mock instance.
func NewMockService(ctrl *gomock.Controller) *MockService {
	mock := &MockService{ctrl: ctrl}
	mock.recorder = &MockServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockService) EXPECT() *MockServiceMockRecorder {
	return m.recorder
}

// AddReview mocks base method.
func (m *MockService) AddReview(data *model.Review) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "AddReview", data)
}

// AddReview indicates an expected call of AddReview.
func (mr *MockServiceMockRecorder) AddReview(data interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddReview", reflect.TypeOf((*MockService)(nil).AddReview), data)
}
