// Code generated by MockGen. DO NOT EDIT.
// Source: handler.go

// Package mock_superlike_post is a generated GoMock package.
package mock_superlike_post

import (
	model "escalateservice/internal/model/domain"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockService is a mock of Service interface.
type MockService struct {
	ctrl     *gomock.Controller
	recorder *MockServiceMockRecorder
}

// MockServiceMockRecorder is the mock recorder for MockService.
type MockServiceMockRecorder struct {
	mock *MockService
}

// NewMockService creates a new mock instance.
func NewMockService(ctrl *gomock.Controller) *MockService {
	mock := &MockService{ctrl: ctrl}
	mock.recorder = &MockServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockService) EXPECT() *MockServiceMockRecorder {
	return m.recorder
}

// AddSuperlikePost mocks base method.
func (m *MockService) AddSuperlikePost(data *model.SuperlikePost) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "AddSuperlikePost", data)
}

// AddSuperlikePost indicates an expected call of AddSuperlikePost.
func (mr *MockServiceMockRecorder) AddSuperlikePost(data interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddSuperlikePost", reflect.TypeOf((*MockService)(nil).AddSuperlikePost), data)
}
